# Generated by Django 4.0.3 on 2022-05-31 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.FilePathField(default='image.png', path='D:\\Python-projects\\djangoBlog\\media\\uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2022, 5, 31)),
        ),
    ]
