# Generated by Django 4.0.3 on 2022-05-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_gallery_path_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
