# Generated by Django 4.0.3 on 2022-03-31 09:49

import datetime
from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_table_alter_categorytranslation_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Custom Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'site_identity',
            },
        ),
        migrations.CreateModel(
            name='CustomText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('plain_text', models.TextField(blank=True, verbose_name='Plain/Markdown Text')),
                ('html_text', models.TextField(blank=True, verbose_name='HTML Text')),
                ('auto_render', models.BooleanField(default=True, verbose_name='Render to HTML using Markdown (on save)')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'site_description',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2022, 3, 31)),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='description',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
    ]
