# Generated by Django 4.0.3 on 2022-03-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customimage_customtext_alter_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtext',
            options={'verbose_name': 'Description', 'verbose_name_plural': 'Descriptions'},
        ),
    ]
