# Generated by Django 4.0.3 on 2022-05-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_gallery_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.ImageField(upload_to='D:/uploads/images/'),
        ),
    ]
