# Generated by Django 4.0.3 on 2022-04-02 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_item_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
    ]
