# Generated by Django 4.0.3 on 2022-04-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_item_order_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
