# Generated by Django 4.0.3 on 2022-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
