# Generated by Django 4.0.3 on 2022-04-07 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_item_menuitem_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuitem',
            table='menu_item',
        ),
    ]
