# Generated by Django 4.0.3 on 2022-04-08 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_menuitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='base_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
    ]
