# Generated by Django 4.0.3 on 2022-04-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_menu_base_url_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='anonymous_only',
            field=models.BooleanField(blank=True, default=False, help_text='Should this item only be shown to non-logged-in users?', verbose_name='Anonymous only'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='login_required',
            field=models.BooleanField(blank=True, default=False, help_text='Should this item only be shown to authenticated users?', verbose_name='Login required'),
        ),
    ]
