# Generated by Django 4.0.3 on 2022-04-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_menuitem_anonymous_only_menuitem_login_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='anonymous_only',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='login_required',
        ),
    ]
